import { Card } from './model';

export const cardsData: Card[] = [
  {
    suit: 'OROS',
    figure: 'AS',
    value: 1,
    url: '/assets/oros/1.svg',
  },
  {
    suit: 'OROS',
    figure: 'DOS',
    value: 2,
    url: '/assets/oros/2.svg',
  },
  {
    suit: 'OROS',
    figure: 'TRES',
    value: 3,
    url: '/assets/oros/3.svg',
  },
  {
    suit: 'OROS',
    figure: 'CUATRO',
    value: 4,
    url: '/assets/oros/4.svg',
  },
  {
    suit: 'OROS',
    figure: 'CINCO',
    value: 5,
    url: '/assets/oros/5.svg',
  },
  {
    suit: 'OROS',
    figure: 'SEIS',
    value: 6,
    url: '/assets/oros/6.svg',
  },
  {
    suit: 'OROS',
    figure: 'SIETE',
    value: 7,
    url: '/assets/oros/7.svg',
  },
  {
    suit: 'OROS',
    figure: 'SOTA',
    value: 0.5,
    url: '/assets/oros/10.svg',
  },
  {
    suit: 'OROS',
    figure: 'CABALLO',
    value: 0.5,
    url: '/assets/oros/11.svg',
  },
  {
    suit: 'OROS',
    figure: 'REY',
    value: 0.5,
    url: '/assets/oros/12.svg',
  },
  {
    suit: 'COPAS',
    figure: 'AS',
    value: 1,
    url: '/assets/copas/1.svg',
  },
  {
    suit: 'COPAS',
    figure: 'DOS',
    value: 2,
    url: '/assets/copas/2.svg',
  },
  {
    suit: 'COPAS',
    figure: 'TRES',
    value: 3,
    url: '/assets/copas/3.svg',
  },
  {
    suit: 'COPAS',
    figure: 'CUATRO',
    value: 4,
    url: '/assets/copas/4.svg',
  },
  {
    suit: 'COPAS',
    figure: 'CINCO',
    value: 5,
    url: '/assets/copas/5.svg',
  },
  {
    suit: 'COPAS',
    figure: 'SEIS',
    value: 6,
    url: '/assets/copas/6.svg',
  },
  {
    suit: 'COPAS',
    figure: 'SIETE',
    value: 7,
    url: '/assets/copas/7.svg',
  },
  {
    suit: 'COPAS',
    figure: 'SOTA',
    value: 0.5,
    url: '/assets/copas/10.svg',
  },
  {
    suit: 'COPAS',
    figure: 'CABALLO',
    value: 0.5,
    url: '/assets/copas/11.svg',
  },
  {
    suit: 'COPAS',
    figure: 'REY',
    value: 0.5,
    url: '/assets/copas/12.svg',
  },
  {
    suit: 'ESPADAS',
    figure: 'AS',
    value: 1,
    url: '/assets/espadas/1.svg',
  },
  {
    suit: 'ESPADAS',
    figure: 'DOS',
    value: 2,
    url: '/assets/espadas/2.svg',
  },
  {
    suit: 'ESPADAS',
    figure: 'TRES',
    value: 3,
    url: '/assets/espadas/3.svg',
  },
  {
    suit: 'ESPADAS',
    figure: 'CUATRO',
    value: 4,
    url: '/assets/espadas/4.svg',
  },
  {
    suit: 'ESPADAS',
    figure: 'CINCO',
    value: 5,
    url: '/assets/espadas/5.svg',
  },
  {
    suit: 'ESPADAS',
    figure: 'SEIS',
    value: 6,
    url: '/assets/espadas/6.svg',
  },
  {
    suit: 'ESPADAS',
    figure: 'SIETE',
    value: 7,
    url: '/assets/espadas/7.svg',
  },
  {
    suit: 'ESPADAS',
    figure: 'SOTA',
    value: 0.5,
    url: '/assets/espadas/10.svg',
  },
  {
    suit: 'ESPADAS',
    figure: 'CABALLO',
    value: 0.5,
    url: '/assets/espadas/11.svg',
  },
  {
    suit: 'ESPADAS',
    figure: 'REY',
    value: 0.5,
    url: '/assets/espadas/12.svg',
  },
  {
    suit: 'BASTOS',
    figure: 'AS',
    value: 1,
    url: '/assets/bastos/1.svg',
  },
  {
    suit: 'BASTOS',
    figure: 'DOS',
    value: 2,
    url: '/assets/bastos/2.svg',
  },
  {
    suit: 'BASTOS',
    figure: 'TRES',
    value: 3,
    url: '/assets/bastos/3.svg',
  },
  {
    suit: 'BASTOS',
    figure: 'CUATRO',
    value: 4,
    url: '/assets/bastos/4.svg',
  },
  {
    suit: 'BASTOS',
    figure: 'CINCO',
    value: 5,
    url: '/assets/bastos/5.svg',
  },
  {
    suit: 'BASTOS',
    figure: 'SEIS',
    value: 6,
    url: '/assets/bastos/6.svg',
  },
  {
    suit: 'BASTOS',
    figure: 'SIETE',
    value: 7,
    url: '/assets/bastos/7.svg',
  },
  {
    suit: 'BASTOS',
    figure: 'SOTA',
    value: 0.5,
    url: '/assets/bastos/10.svg',
  },
  {
    suit: 'BASTOS',
    figure: 'CABALLO',
    value: 0.5,
    url: '/assets/bastos/11.svg',
  },
  {
    suit: 'BASTOS',
    figure: 'REY',
    value: 0.5,
    url: '/assets/bastos/12.svg',
  },
];
